/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/~__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const TrackIndexLazyImport = createFileRoute('/track/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/~index.lazy').then((d) => d.Route))

const TrackIndexLazyRoute = TrackIndexLazyImport.update({
  id: '/track/',
  path: '/track/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/~track/~index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/track/': {
      id: '/track/'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/track': typeof TrackIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/track': typeof TrackIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/track/': typeof TrackIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/track'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/track'
  id: '__root__' | '/' | '/track/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  TrackIndexLazyRoute: typeof TrackIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  TrackIndexLazyRoute: TrackIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "~__root.tsx",
      "children": [
        "/",
        "/track/"
      ]
    },
    "/": {
      "filePath": "~index.lazy.tsx"
    },
    "/track/": {
      "filePath": "~track/~index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
